# Generated by Django 3.2.5 on 2021-08-17 09:46

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('main', '0002_auto_20210817_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('pic', models.ImageField(blank=True, upload_to='user_pics/')),
                ('git', models.URLField()),
                ('twitter', models.URLField()),
                ('linkedin', models.URLField()),
                ('email', models.CharField(max_length=48)),
                ('phone', models.CharField(max_length=48)),
                ('projectsdone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstline', models.CharField(max_length=48)),
                ('secondline', models.CharField(max_length=48)),
                ('thirdline', models.CharField(max_length=48)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creator')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('Img', models.ImageField(upload_to='Project_images/')),
                ('description', models.TextField()),
                ('git', models.URLField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smalltxt', models.CharField(max_length=24)),
                ('bigtxt', models.CharField(max_length=24)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.creator')),
            ],
        ),
    ]
