# Generated by Django 3.2.5 on 2021-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bio_creator_project_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='about',
            field=models.CharField(default='', max_length=50),
        ),
    ]
