# Generated by Django 3.2.5 on 2021-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_creator_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='creator',
            name='phone',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='services',
            name='firstline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='services',
            name='secondline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='services',
            name='thirdline',
            field=models.CharField(max_length=72),
        ),
    ]
