# Generated by Django 3.2.5 on 2021-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_creator_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='about',
            field=models.TextField(max_length=300),
        ),
    ]
