# Generated by Django 3.2.5 on 2021-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_creator_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='ffirstline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='fsecondline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='fthirdline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='sfirstline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='ssecondline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='sthirdline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='tfirstline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='tsecondline',
            field=models.CharField(default='', max_length=72),
        ),
        migrations.AddField(
            model_name='creator',
            name='tthirdline',
            field=models.CharField(default='', max_length=72),
        ),
    ]
