# Generated by Django 3.2.5 on 2021-08-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210817_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='ffirstline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='fsecondline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='fthirdline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='sfirstline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='ssecondline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='sthirdline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tfirstline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tsecondline',
            field=models.CharField(max_length=72),
        ),
        migrations.AlterField(
            model_name='creator',
            name='tthirdline',
            field=models.CharField(max_length=72),
        ),
        migrations.DeleteModel(
            name='services',
        ),
    ]
