# Generated by Django 3.2.5 on 2021-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_exp_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstline', models.CharField(max_length=72)),
                ('secondline', models.CharField(max_length=72)),
                ('thirdline', models.CharField(max_length=72)),
            ],
        ),
        migrations.RemoveField(
            model_name='creator',
            name='ffirstline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='fsecondline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='fthirdline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='sfirstline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='ssecondline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='sthirdline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='tfirstline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='tsecondline',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='tthirdline',
        ),
    ]
