# Generated by Django 3.2.5 on 2021-08-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='pic',
            field=models.FileField(blank=True, upload_to='user_pics/'),
        ),
    ]
