# Generated by Django 3.2.5 on 2021-08-17 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_creator_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='pic',
            field=models.ImageField(blank=True, upload_to='user_pics/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
