# Generated by Django 3.2.5 on 2021-08-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210818_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='secondaboutline',
        ),
        migrations.AlterField(
            model_name='creator',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='creator',
            name='firstaboutline',
            field=models.CharField(max_length=500),
        ),
    ]
